// development/libs/dafel-banda-vectorization/components/react/src/components/BandLayer.tsx
/**
 * Band Layer Component
 * Individual layer renderer with performance optimizations
 */

import React, { memo } from 'react';
import clsx from 'clsx';
import { BandLayer as BandLayerType } from '../../../shared/types';

interface BandLayerProps {
  layer: BandLayerType;
  index: number;
  instanceId: string;
  animation: string;
  interactive: boolean;
  performance: 'low' | 'medium' | 'high';
  onError: (error: Error) => void;
}

export const BandLayer: React.FC<BandLayerProps> = memo(({
  layer,
  index,
  instanceId,
  animation,
  interactive,
  performance,
  onError
}) => {
  // Performance optimizations based on level
  const shouldUseFilter = performance === 'high' && layer.hasFilter;
  const shouldOptimizeRendering = performance === 'low';

  const layerStyle = {
    ...(shouldOptimizeRendering && {
      shapeRendering: 'optimizeSpeed' as const,
      colorRendering: 'optimizeSpeed' as const,
    }),
    ...(performance === 'high' && {
      willChange: 'transform, opacity',
    }),
  };

  const handleLayerError = () => {
    onError(new Error(`Failed to render layer ${layer.id}`));
  };

  return (
    <g
      id={`layer-${layer.id}-${layer.name}-${instanceId}`}
      className={clsx('band-layer', {
        'band-layer--has-grid': layer.hasGrid,
        'band-layer--has-filter': shouldUseFilter,
        'band-layer--interactive': interactive,
        'band-layer--optimized': shouldOptimizeRendering,
      })}
      opacity={layer.opacity}
      style={layerStyle}
      filter={shouldUseFilter ? `url(#${layer.filter}-${instanceId})` : undefined}
      onError={handleLayerError}
    >
      {/* Base path */}
      <path
        d={layer.path}
        fill={`url(#${layer.gradient}-${instanceId})`}
        className="band-path"
        vectorEffect={shouldOptimizeRendering ? 'non-scaling-stroke' : undefined}
      />

      {/* Grid overlay */}
      {layer.hasGrid && (
        <path
          d={layer.path}
          fill={`url(#${layer.gridPattern}-${instanceId})`}
          className="band-grid-overlay"
          vectorEffect={shouldOptimizeRendering ? 'non-scaling-stroke' : undefined}
        />
      )}
    </g>
  );
});

BandLayer.displayName = 'BandLayer';

export default BandLayer;

// dafel-banda-vectorization/components/vue/src/components/BandLayer.vue
<!--
  Band Layer Component for Vue
  Individual layer renderer with performance optimizations
-->

<template>
  <g
    :id="`layer-${layer.id}-${layer.name}-${instanceId}`"
    :class="layerClasses"
    :opacity="layer.opacity"
    :style="layerStyles"
    :filter="shouldUseFilter ? `url(#${layer.filter}-${instanceId})` : undefined"
    @error="handleError"
  >
    <!-- Base path -->
    <path
      :d="layer.path"
      :fill="`url(#${layer.gradient}-${instanceId})`"
      class="band-path"
      :vector-effect="shouldOptimizeRendering ? 'non-scaling-stroke' : undefined"
    />

    <!-- Grid overlay -->
    <path
      v-if="layer.hasGrid"
      :d="layer.path"
      :fill="`url(#${layer.gridPattern}-${instanceId})`"
      class="band-grid-overlay"
      :vector-effect="shouldOptimizeRendering ? 'non-scaling-stroke' : undefined"
    />
  </g>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { BandLayer as BandLayerType } from '../../../shared/types'

interface Props {
  layer: BandLayerType
  index: number
  instanceId: string
  animation: string
  interactive: boolean
  performance: 'low' | 'medium' | 'high'
}

const props = defineProps<Props>()

const emit = defineEmits<{
  error: [error: Error]
}>()

// Computed properties
const shouldUseFilter = computed(() => 
  props.performance === 'high' && props.layer.hasFilter
)

const shouldOptimizeRendering = computed(() => 
  props.performance === 'low'
)

const layerClasses = computed(() => [
  'band-layer',
  {
    'band-layer--has-grid': props.layer.hasGrid,
    'band-layer--has-filter': shouldUseFilter.value,
    'band-layer--interactive': props.interactive,
    'band-layer--optimized': shouldOptimizeRendering.value,
  }
])

const layerStyles = computed(() => ({
  ...(shouldOptimizeRendering.value && {
    shapeRendering: 'optimizeSpeed',
    colorRendering: 'optimizeSpeed',
  }),
  ...(props.performance === 'high' && {
    willChange: 'transform, opacity',
  }),
}))

// Methods
const handleError = () => {
  emit('error', new Error(`Failed to render layer ${props.layer.id}`))
}
</script>

<style scoped>
.band-layer {
  transition: opacity 0.3s ease;
}

.band-layer--interactive:hover {
  opacity: 1;
}

.band-path {
  transition: fill 0.3s ease;
}

.band-grid-overlay {
  pointer-events: none;
  mix-blend-mode: overlay;
}

.band-layer--optimized .band-path,
.band-layer--optimized .band-grid-overlay {
  shape-rendering: optimizeSpeed;
  color-rendering: optimizeSpeed;
}
</style>
