// libs/dafel-banda-vectorization/components/vue/src/DafelBandaAnimated.vue
<!--
  Dafel Banda Animated Vue 3 Component
  Full-featured component with Vue Motion animations
-->

<template>
  <svg
    ref="svgRef"
    :width="width"
    :height="height"
    :viewBox="`0 0 ${width} ${height}`"
    xmlns="http://www.w3.org/2000/svg"
    :class="componentClasses"
    :style="componentStyles"
    :aria-label="ariaLabel"
    :role="accessibilityConfig?.role || 'img'"
    :tabindex="interactive && accessibilityConfig?.focusable ? accessibilityConfig.tabIndex || 0 : undefined"
    @mouseenter="handleInteraction"
    @click="handleInteraction"
    @focus="handleInteraction"
    @load="handleLoad"
    v-motion
    :initial="containerVariants.hidden"
    :enter="containerVariants.visible"
    :leave="containerVariants.hidden"
  >
    <!-- SVG Definitions -->
    <SVGDefinitions 
      :instance-id="instanceId"
      :theme-config="themeConfig"
    />

    <!-- Background -->
    <rect 
      :width="width" 
      :height="height" 
      :fill="themeConfig?.colors?.background || '#F8FBFD'" 
    />

    <!-- Animated Layers -->
    <g
      v-for="(layer, index) in layerData"
      :key="layer.id"
      :id="`layer-${layer.id}-${layer.name}-${instanceId}`"
      :class="getLayerClasses(layer)"
      :opacity="layer.opacity"
      :style="getLayerStyles(layer)"
      v-motion
      :initial="getLayerInitial(index)"
      :enter="getLayerEnter(layer, index)"
      :variants="layerVariants[finalAnimation]"
      :custom="getLayerCustomProps(layer, index)"
      @mouseenter="interactive ? (e: Event) => handleLayerInteraction(e, layer.id) : undefined"
      @click="interactive ? (e: Event) => handleLayerInteraction(e, layer.id) : undefined"
      @focus="interactive ? (e: Event) => handleLayerInteraction(e, layer.id) : undefined"
    >
      <!-- Base path -->
      <path
        :d="layer.path"
        :fill="`url(#${layer.gradient}-${instanceId})`"
        class="band-path"
      />

      <!-- Grid overlay -->
      <path
        v-if="layer.hasGrid"
        :d="layer.path"
        :fill="`url(#${layer.gridPattern}-${instanceId})`"
        class="band-grid-overlay"
      />
    </g>
  </svg>
</template>

<script setup lang="ts">
import { computed, ref, reactive, onMounted, watch } from 'vue'
import { useMotion } from '@vueuse/motion'
import { useIntersectionObserver } from '@vueuse/core'
import { nanoid } from 'nanoid'
import { 
  DafelBandaProps, 
  LAYER_DEFINITIONS, 
  shouldReduceMotion,
  getLayerDelay
} from '../../shared/types'
import SVGDefinitions from './components/SVGDefinitions.vue'

// Props
const props = withDefaults(defineProps<DafelBandaProps>(), {
  animation: 'fadeIn',
  width: 1280,
  height: 720,
  interactive: false,
  className: '',
  ariaLabel: 'Dafel Banda animated decorative element',
  reducedMotion: false,
  lazy: true,
  performance: 'medium'
})

// Emits
const emit = defineEmits<{
  hover: [event: Event]
  click: [event: Event]
  focus: [event: Event]
  load: []
  error: [error: Error]
}>()

// Template refs
const svgRef = ref<SVGSVGElement>()

// Reactive state
const state = reactive({
  instanceId: nanoid(),
  isVisible: false,
  isPlaying: false
})

// Intersection observer for visibility
const { stop } = useIntersectionObserver(
  svgRef,
  ([{ isIntersecting }]) => {
    state.isVisible = isIntersecting
  },
  { threshold: 0.3, rootMargin: '-100px' }
)

// Computed properties
const motionReduced = computed(() => 
  shouldReduceMotion({ 
    reducedMotion: props.reducedMotion, 
    accessibilityConfig: props.accessibilityConfig 
  })
)

const finalAnimation = computed(() => 
  motionReduced.value ? 'none' : props.animation
)

const layerData = computed(() => LAYER_DEFINITIONS)

const instanceId = computed(() => state.instanceId)

const componentClasses = computed(() => [
  'dafel-banda',
  'dafel-banda--animated',
  {
    'dafel-banda--interactive': props.interactive,
    'dafel-banda--reduced-motion': motionReduced.value,
    'dafel-banda--visible': state.isVisible,
    [`dafel-banda--${props.performance}`]: props.performance !== 'medium',
    [`dafel-banda--${finalAnimation.value}`]: finalAnimation.value !== 'none',
  },
  props.className
])

const componentStyles = computed(() => ({
  overflow: 'hidden',
  ...(props.performance === 'high' && {
    willChange: 'transform, opacity',
    transform: 'translateZ(0)'
  })
}))

// Animation variants
const containerVariants = computed(() => ({
  hidden: {
    opacity: 0,
    scale: 0.95,
    y: 50
  },
  visible: {
    opacity: 1,
    scale: 1,
    y: 0,
    transition: {
      duration: props.animationConfig?.duration || 1200,
      ease: props.animationConfig?.easing || 'ease-out',
      staggerChildren: 100
    }
  }
}))

const layerVariants = computed(() => ({
  fadeIn: {
    hidden: { opacity: 0, y: 30, scale: 0.95 },
    visible: (custom: any) => ({
      opacity: custom.baseOpacity,
      y: 0,
      scale: 1,
      transition: {
        duration: 1000,
        delay: custom.delay,
        ease: 'ease-out'
      }
    })
  },
  wave: {
    animate: (custom: any) => ({
      x: [-8, 8, -8],
      y: [-3, 3, -3],
      transition: {
        duration: props.animationConfig?.duration || 4000,
        delay: custom.delay,
        repeat: props.animationConfig?.repeat === false ? 0 : Infinity,
        ease: 'ease-in-out',
        repeatType: 'reverse'
      }
    })
  },
  pulse: {
    animate: (custom: any) => ({
      scale: [1, 1.02, 1],
      opacity: [
        custom.baseOpacity,
        Math.min(custom.baseOpacity + 0.15, 1),
        custom.baseOpacity
      ],
      transition: {
        duration: 3000,
        delay: custom.delay,
        repeat: props.animationConfig?.repeat === false ? 0 : Infinity,
        ease: 'ease-in-out'
      }
    })
  },
  interactive: {
    rest: { scale: 1, y: 0 },
    hover: (custom: any) => ({
      scale: 1.02,
      y: -2,
      opacity: Math.min(custom.baseOpacity + 0.1, 1),
      transition: {
        duration: 300,
        ease: 'ease-out'
      }
    }),
    tap: { scale: 0.98 }
  }
}))

// Methods
const getLayerClasses = (layer: any) => [
  'band-layer',
  {
    'band-layer--has-grid': layer.hasGrid,
    'band-layer--interactive': props.interactive
  }
]

const getLayerStyles = (layer: any) => ({
  cursor: props.interactive ? 'pointer' : 'default',
  ...(layer.hasFilter && props.performance === 'high' && {
    filter: `url(#${layer.filter}-${instanceId.value})`
  })
})

const getLayerInitial = (index: number) => {
  switch (finalAnimation.value) {
    case 'fadeIn':
      return 'hidden'
    default:
      return {}
  }
}

const getLayerEnter = (layer: any, index: number) => {
  switch (finalAnimation.value) {
    case 'fadeIn':
      return state.isVisible ? 'visible' : 'hidden'
    case 'wave':
    case 'pulse':
      return 'animate'
    case 'interactive':
      return props.interactive ? 'rest' : {}
    default:
      return {}
  }
}

const getLayerCustomProps = (layer: any, index: number) => ({
  baseOpacity: layer.opacity,
  delay: getLayerDelay(index),
  duration: 4000 - getLayerDelay(index),
  originalPath: layer.path
})

const handleInteraction = (event: Event) => {
  if (!props.interactive) return
  
  switch (event.type) {
    case 'mouseenter':
    case 'mouseover':
      emit('hover', event)
      break
    case 'click':
      emit('click', event)
      break
    case 'focus':
      emit('focus', event)
      break
  }
}

const handleLayerInteraction = (event: Event, layerId: number) => {
  if (!props.interactive) return
  
  switch (event.type) {
    case 'mouseenter':
      emit('hover', event)
      break
    case 'click':
      emit('click', event)
      break
    case 'focus':
      emit('focus', event)
      break
  }
}

const handleLoad = () => {
  emit('load')
}

// Watch for visibility changes to control animations
watch(() => state.isVisible, (isVisible) => {
  if (isVisible) {
    state.isPlaying = true
  }
})

// Cleanup
onMounted(() => {
  return () => {
    stop()
  }
})

// Expose public API
defineExpose({
  svgElement: svgRef,
  isVisible: computed(() => state.isVisible),
  isPlaying: computed(() => state.isPlaying),
  instanceId,
  play: () => { state.isPlaying = true },
  pause: () => { state.isPlaying = false },
  reset: () => { 
    state.isPlaying = false
    // Reset to initial state
  }
})
</script>

<style scoped>
.dafel-banda {
  display: block;
  max-width: 100%;
  height: auto;
}

.dafel-banda--animated {
  transition: all 0.3s ease;
}

.dafel-banda--interactive {
  cursor: pointer;
}

.band-layer {
  transition: all 0.3s ease;
}

.band-layer--interactive:hover {
  opacity: 1 !important;
}

.band-path {
  vector-effect: non-scaling-stroke;
}

.band-grid-overlay {
  pointer-events: none;
}

.dafel-banda--reduced-motion,
.dafel-banda--reduced-motion * {
  animation-duration: 0.01ms !important;
  animation-iteration-count: 1 !important;
  transition-duration: 0.01ms !important;
}

@media (prefers-reduced-motion: reduce) {
  .dafel-banda,
  .dafel-banda * {
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.01ms !important;
  }
}

@media (max-width: 768px) {
  .dafel-banda {
    max-height: 300px;
  }
}
</style>

// versions/v0.0.0/libs/dafel-banda-vectorization/components/react/src/DafelBandaAnimated.tsx
/**
 * Dafel Banda Animated React Component
 * Full-featured component with Framer Motion animations
 */

import React, { useMemo, forwardRef, useRef } from 'react';
import { motion, useInView, useScroll, useTransform, AnimatePresence } from 'framer-motion';
import clsx from 'clsx';
import { DafelBandaProps, LAYER_DEFINITIONS, shouldReduceMotion, getLayerDelay } from '../../shared/types';
import { SVGDefinitions } from './components/SVGDefinitions';

export const DafelBandaAnimated = forwardRef<SVGSVGElement, DafelBandaProps>((
  {
    animation = 'fadeIn',
    width = 1280,
    height = 720,
    interactive = false,
    className = '',
    ariaLabel = 'Dafel Banda animated decorative element',
    reducedMotion = false,
    lazy = true,
    performance = 'medium',
    animationConfig,
    accessibilityConfig,
    themeConfig,
    onHover,
    onClick,
    onFocus,
    onLoad,
    onError,
    ...props
  },
  ref
) => {
  const containerRef = useRef<SVGSVGElement>(null);
  const isInView = useInView(containerRef, { 
    once: true, 
    amount: 0.3,
    margin: '-100px'
  });

  // Check if motion should be reduced
  const motionReduced = shouldReduceMotion({ reducedMotion, accessibilityConfig });
  const finalAnimation = motionReduced ? 'none' : animation;

  // Scroll-based animation setup
  const { scrollYProgress } = useScroll({
    target: containerRef,
    offset: ['start end', 'end start']
  });

  // Performance optimizations
  const layerData = useMemo(() => LAYER_DEFINITIONS, []);
  const instanceId = useMemo(() => Math.random().toString(36).substr(2, 9), []);

  // Animation variants
  const containerVariants = useMemo(() => ({
    hidden: {
      opacity: 0,
      scale: 0.95,
      y: 50,
    },
    visible: {
      opacity: 1,
      scale: 1,
      y: 0,
      transition: {
        duration: animationConfig?.duration || 1.2,
        ease: animationConfig?.easing || [0.4, 0, 0.2, 1],
        staggerChildren: 0.1,
      }
    }
  }), [animationConfig]);

  const layerVariants = useMemo(() => ({
    fadeIn: {
      hidden: { opacity: 0, y: 30, scale: 0.95 },
      visible: (custom: any) => ({
        opacity: custom.baseOpacity,
        y: 0,
        scale: 1,
        transition: {
          duration: 1.0,
          delay: custom.delay,
          ease: [0.4, 0, 0.2, 1]
        }
      })
    },
    wave: {
      animate: (custom: any) => ({
        x: [-8, 8, -8],
        y: [-3, 3, -3],
        transition: {
          duration: animationConfig?.duration || 4,
          delay: custom.delay,
          repeat: animationConfig?.repeat === false ? 0 : Infinity,
          ease: 'easeInOut',
          repeatType: 'reverse' as const
        }
      })
    },
    pulse: {
      animate: (custom: any) => ({
        scale: [1, 1.02, 1],
        opacity: [
          custom.baseOpacity,
          Math.min(custom.baseOpacity + 0.15, 1),
          custom.baseOpacity
        ],
        transition: {
          duration: 3,
          delay: custom.delay,
          repeat: animationConfig?.repeat === false ? 0 : Infinity,
          ease: 'easeInOut'
        }
      })
    },
    morphing: {
      animate: (custom: any) => ({
        d: [
          custom.originalPath,
          custom.morphedPath || custom.originalPath,
          custom.originalPath
        ],
        transition: {
          duration: 5,
          delay: custom.delay,
          repeat: animationConfig?.repeat === false ? 0 : Infinity,
          ease: 'easeInOut'
        }
      })
    },
    interactive: {
      rest: { scale: 1, y: 0 },
      hover: (custom: any) => ({
        scale: 1.02,
        y: -2,
        opacity: Math.min(custom.baseOpacity + 0.1, 1),
        transition: {
          duration: 0.3,
          ease: [0.4, 0, 0.2, 1]
        }
      }),
      tap: { scale: 0.98 }
    }
  }), [animationConfig]);

  // Generate morph paths for morphing animation
  const getMorphedPath = (originalPath: string, factor: number = 0.1): string => {
    // Simple path morphing - in production, use a proper SVG morphing library
    return originalPath.replace(/(\d+)/g, (match) => {
      const num = parseInt(match);
      const variation = Math.sin(num * 0.01) * factor * num;
      return Math.round(num + variation).toString();
    });
  };

  // Event handlers
  const handleLayerInteraction = (event: any, layerId: number) => {
    if (!interactive) return;
    
    switch (event.type) {
      case 'mouseenter':
        onHover?.(event);
        break;
      case 'click':
        onClick?.(event);
        break;
      case 'focus':
        onFocus?.(event);
        break;
    }
  };

  const getAnimationProps = (layer: any, index: number) => {
    const customProps = {
      baseOpacity: layer.opacity,
      delay: getLayerDelay(index),
      originalPath: layer.path,
      morphedPath: getMorphedPath(layer.path)
    };

    switch (finalAnimation) {
      case 'fadeIn':
        return {
          initial: 'hidden',
          animate: isInView ? 'visible' : 'hidden',
          variants: layerVariants.fadeIn,
          custom: customProps
        };
      
      case 'wave':
      case 'pulse':
        return {
          animate: 'animate',
          variants: layerVariants[finalAnimation],
          custom: customProps
        };
      
      case 'morphing':
        return {
          animate: 'animate',
          variants: layerVariants.morphing,
          custom: customProps
        };
      
      case 'interactive':
        return interactive ? {
          initial: 'rest',
          whileHover: 'hover',
          whileTap: 'tap',
          variants: layerVariants.interactive,
          custom: customProps
        } : {};
      
      case 'scroll':
        return {
          style: {
            y: useTransform(scrollYProgress, [0, 1], [0, (index + 1) * 15])
          }
        };
      
      default:
        return {};
    }
  };

  return (
    <AnimatePresence>
      <motion.svg
        ref={(element) => {
          containerRef.current = element;
          if (typeof ref === 'function') ref(element);
          else if (ref) ref.current = element;
        }}
        width={width}
        height={height}
        viewBox={`0 0 ${width} ${height}`}
        xmlns="http://www.w3.org/2000/svg"
        className={clsx(
          'dafel-banda',
          'dafel-banda--animated',
          {
            'dafel-banda--interactive': interactive,
            'dafel-banda--reduced-motion': motionReduced,
            [`dafel-banda--${performance}`]: performance !== 'medium',
            [`dafel-banda--${finalAnimation}`]: finalAnimation !== 'none',
          },
          className
        )}
        style={{
          overflow: 'hidden',
          ...(performance === 'high' && {
            willChange: 'transform, opacity',
            transform: 'translateZ(0)',
          }),
        }}
        initial="hidden"
        animate={isInView ? "visible" : "hidden"}
        variants={containerVariants}
        aria-label={ariaLabel}
        role={accessibilityConfig?.role || 'img'}
        onLoad={() => onLoad?.()}
        {...props}
      >
        {/* SVG Definitions */}
        <SVGDefinitions 
          instanceId={instanceId}
          themeConfig={themeConfig}
        />

        {/* Background */}
        <rect 
          width={width} 
          height={height} 
          fill={themeConfig?.colors?.background || '#F8FBFD'} 
        />

        {/* Animated Layers */}
        {layerData.map((layer, index) => (
          <motion.g
            key={layer.id}
            id={`layer-${layer.id}-${layer.name}-${instanceId}`}
            className={clsx('band-layer', {
              'band-layer--has-grid': layer.hasGrid,
              'band-layer--interactive': interactive
            })}
            opacity={layer.opacity}
            {...getAnimationProps(layer, index)}
            onMouseEnter={interactive ? (e) => handleLayerInteraction(e, layer.id) : undefined}
            onClick={interactive ? (e) => handleLayerInteraction(e, layer.id) : undefined}
            onFocus={interactive ? (e) => handleLayerInteraction(e, layer.id) : undefined}
            style={{
              cursor: interactive ? 'pointer' : 'default',
              ...(layer.hasFilter && performance === 'high' && {
                filter: `url(#${layer.filter}-${instanceId})`
              })
            }}
          >
            {/* Base path */}
            <motion.path
              d={layer.path}
              fill={`url(#${layer.gradient}-${instanceId})`}
              className="band-path"
            />

            {/* Grid overlay */}
            {layer.hasGrid && (
              <motion.path
                d={layer.path}
                fill={`url(#${layer.gridPattern}-${instanceId})`}
                className="band-grid-overlay"
              />
            )}
          </motion.g>
        ))}
      </motion.svg>
    </AnimatePresence>
  );
});

DafelBandaAnimated.displayName = 'DafelBandaAnimated';

export default DafelBandaAnimated;
