// development/libs/dafel-banda-vectorization/components/react/src/DafelBanda.tsx
/**
 * Dafel Banda React Component - Basic Implementation
 * Production-ready SVG component with TypeScript support
 */

import React, { useMemo, forwardRef } from 'react';
import clsx from 'clsx';
import { DafelBandaProps, LAYER_DEFINITIONS, shouldReduceMotion } from '../../shared/types';
import { SVGDefinitions } from './components/SVGDefinitions';
import { BandLayer } from './components/BandLayer';

export interface DafelBandaBasicProps extends Omit<DafelBandaProps, 'animation'> {
  /** Animation type - basic component supports limited animations */
  animation?: 'none' | 'fadeIn';
}

export const DafelBanda = forwardRef<SVGSVGElement, DafelBandaBasicProps>((
  {
    animation = 'fadeIn',
    width = 1280,
    height = 720,
    interactive = false,
    className = '',
    ariaLabel = 'Dafel Banda decorative element',
    reducedMotion = false,
    lazy = true,
    performance = 'medium',
    accessibilityConfig,
    themeConfig,
    onHover,
    onClick,
    onFocus,
    onLoad,
    onError,
    ...props
  },
  ref
) => {
  // Check if motion should be reduced
  const motionReduced = shouldReduceMotion({ reducedMotion, accessibilityConfig });
  const finalAnimation = motionReduced ? 'none' : animation;

  // Performance optimizations
  const layerData = useMemo(() => LAYER_DEFINITIONS, []);
  
  // Calculate responsive viewBox
  const viewBox = useMemo(() => `0 0 ${width} ${height}`, [width, height]);

  // Generate unique IDs to avoid conflicts
  const instanceId = useMemo(() => Math.random().toString(36).substr(2, 9), []);

  // Apply theme customizations
  const customStyles = useMemo(() => {
    if (!themeConfig) return {};
    
    return {
      filter: themeConfig.darkMode ? 'invert(1) hue-rotate(180deg)' : undefined,
      opacity: themeConfig.highContrast ? 0.9 : undefined,
    };
  }, [themeConfig]);

  // Event handlers
  const handleLoad = () => {
    onLoad?.();
  };

  const handleError = (error: Error) => {
    console.error('DafelBanda component error:', error);
    onError?.(error);
  };

  const handleInteraction = (event: React.MouseEvent | React.FocusEvent) => {
    if (!interactive) return;
    
    switch (event.type) {
      case 'mouseenter':
      case 'mouseover':
        onHover?.(event.nativeEvent);
        break;
      case 'click':
        onClick?.(event.nativeEvent);
        break;
      case 'focus':
        onFocus?.(event.nativeEvent);
        break;
    }
  };

  return (
    <svg
      ref={ref}
      width={width}
      height={height}
      viewBox={viewBox}
      xmlns="http://www.w3.org/2000/svg"
      className={clsx(
        'dafel-banda',
        'dafel-banda--basic',
        {
          'dafel-banda--interactive': interactive,
          'dafel-banda--reduced-motion': motionReduced,
          [`dafel-banda--${performance}`]: performance !== 'medium',
        },
        className
      )}
      style={{
        overflow: 'hidden',
        ...customStyles,
        ...(performance === 'high' && {
          willChange: 'transform, opacity',
          transform: 'translateZ(0)', // Force GPU acceleration
        }),
      }}
      aria-label={ariaLabel}
      role={accessibilityConfig?.role || 'img'}
      tabIndex={interactive && accessibilityConfig?.focusable ? accessibilityConfig.tabIndex || 0 : undefined}
      onMouseEnter={interactive ? handleInteraction : undefined}
      onClick={interactive ? handleInteraction : undefined}
      onFocus={interactive ? handleInteraction : undefined}
      onLoad={handleLoad}
      onError={() => handleError(new Error('SVG load error'))}
      {...props}
    >
      {/* SVG Definitions */}
      <SVGDefinitions 
        instanceId={instanceId}
        themeConfig={themeConfig}
      />

      {/* Background */}
      <rect 
        width={width} 
        height={height} 
        fill={themeConfig?.colors?.background || '#F8FBFD'} 
      />

      {/* Band Layers */}
      {layerData.map((layer, index) => (
        <BandLayer
          key={layer.id}
          layer={layer}
          index={index}
          instanceId={instanceId}
          animation={finalAnimation}
          interactive={interactive}
          performance={performance}
          onError={handleError}
        />
      ))}
    </svg>
  );
});

DafelBanda.displayName = 'DafelBanda';

export default DafelBanda;

// dafel-banda-vectorization/components/vue/src/DafelBanda.vue
<!--
  Dafel Banda Vue 3 Component - Basic Implementation
  Production-ready SVG component with Composition API
-->

<template>
  <svg
    ref="svgRef"
    :width="width"
    :height="height"
    :viewBox="`0 0 ${width} ${height}`"
    xmlns="http://www.w3.org/2000/svg"
    :class="componentClasses"
    :style="componentStyles"
    :aria-label="ariaLabel"
    :role="accessibilityConfig?.role || 'img'"
    :tabindex="interactive && accessibilityConfig?.focusable ? accessibilityConfig.tabIndex || 0 : undefined"
    @mouseenter="handleInteraction"
    @click="handleInteraction"
    @focus="handleInteraction"
    @load="handleLoad"
    @error="handleError"
  >
    <!-- SVG Definitions -->
    <SVGDefinitions 
      :instance-id="instanceId"
      :theme-config="themeConfig"
    />

    <!-- Background -->
    <rect 
      :width="width" 
      :height="height" 
      :fill="themeConfig?.colors?.background || '#F8FBFD'" 
    />

    <!-- Band Layers -->
    <BandLayer
      v-for="(layer, index) in layerData"
      :key="layer.id"
      :layer="layer"
      :index="index"
      :instance-id="instanceId"
      :animation="finalAnimation"
      :interactive="interactive"
      :performance="performance"
      @error="handleLayerError"
    />
  </svg>
</template>

<script setup lang="ts">
import { computed, ref, onMounted, reactive } from 'vue'
import { nanoid } from 'nanoid'
import { 
  DafelBandaProps, 
  LAYER_DEFINITIONS, 
  shouldReduceMotion 
} from '../../shared/types'
import SVGDefinitions from './components/SVGDefinitions.vue'
import BandLayer from './components/BandLayer.vue'

// Props with defaults
interface Props extends Partial<DafelBandaProps> {
  animation?: 'none' | 'fadeIn'
}

const props = withDefaults(defineProps<Props>(), {
  animation: 'fadeIn',
  width: 1280,
  height: 720,
  interactive: false,
  className: '',
  ariaLabel: 'Dafel Banda decorative element',
  reducedMotion: false,
  lazy: true,
  performance: 'medium'
})

// Emits
const emit = defineEmits<{
  hover: [event: Event]
  click: [event: Event]
  focus: [event: Event]
  load: []
  error: [error: Error]
}>()

// Template refs
const svgRef = ref<SVGSVGElement>()

// Reactive state
const state = reactive({
  instanceId: nanoid(),
  isLoaded: false,
  hasError: false
})

// Computed properties
const motionReduced = computed(() => 
  shouldReduceMotion({ 
    reducedMotion: props.reducedMotion, 
    accessibilityConfig: props.accessibilityConfig 
  })
)

const finalAnimation = computed(() => 
  motionReduced.value ? 'none' : props.animation
)

const layerData = computed(() => LAYER_DEFINITIONS)

const instanceId = computed(() => state.instanceId)

const componentClasses = computed(() => [
  'dafel-banda',
  'dafel-banda--basic',
  {
    'dafel-banda--interactive': props.interactive,
    'dafel-banda--reduced-motion': motionReduced.value,
    [`dafel-banda--${props.performance}`]: props.performance !== 'medium',
  },
  props.className
])

const componentStyles = computed(() => ({
  overflow: 'hidden',
  ...applyThemeStyles(),
  ...(props.performance === 'high' && {
    willChange: 'transform, opacity',
    transform: 'translateZ(0)' // Force GPU acceleration
  })
}))

// Methods
const applyThemeStyles = () => {
  if (!props.themeConfig) return {}
  
  return {
    filter: props.themeConfig.darkMode ? 'invert(1) hue-rotate(180deg)' : undefined,
    opacity: props.themeConfig.highContrast ? 0.9 : undefined,
  }
}

const handleInteraction = (event: Event) => {
  if (!props.interactive) return
  
  switch (event.type) {
    case 'mouseenter':
    case 'mouseover':
      emit('hover', event)
      break
    case 'click':
      emit('click', event)
      break
    case 'focus':
      emit('focus', event)
      break
  }
}

const handleLoad = () => {
  state.isLoaded = true
  emit('load')
}

const handleError = () => {
  const error = new Error('SVG load error')
  state.hasError = true
  handleLayerError(error)
}

const handleLayerError = (error: Error) => {
  console.error('DafelBanda component error:', error)
  emit('error', error)
}

// Lifecycle
onMounted(() => {
  state.isLoaded = true
})

// Expose public API
defineExpose({
  svgElement: svgRef,
  isLoaded: computed(() => state.isLoaded),
  hasError: computed(() => state.hasError),
  instanceId
})
</script>

<style scoped>
.dafel-banda {
  display: block;
  max-width: 100%;
  height: auto;
}

.dafel-banda--interactive {
  cursor: pointer;
}

.dafel-banda--interactive:hover {
  transform: scale(1.01);
  transition: transform 0.2s ease;
}

.dafel-banda--reduced-motion,
.dafel-banda--reduced-motion * {
  animation-duration: 0.01ms !important;
  animation-iteration-count: 1 !important;
  transition-duration: 0.01ms !important;
}

.dafel-banda--high {
  image-rendering: -webkit-optimize-contrast;
  image-rendering: crisp-edges;
}

.dafel-banda--low {
  image-rendering: optimizeSpeed;
}

@media (prefers-reduced-motion: reduce) {
  .dafel-banda,
  .dafel-banda * {
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.01ms !important;
  }
}
</style>
