// production/libs/dafel-banda-vectorization/components/svelte/src/lib/DafelBandaAnimated.svelte
<!--
  Dafel Banda Animated Svelte Component
  Full-featured component with Svelte motion and animations
-->

<script lang="ts">
  import { onMount, onDestroy, createEventDispatcher, tick } from 'svelte';
  import { tweened } from 'svelte/motion';
  import { cubicOut, elasticOut, sineInOut } from 'svelte/easing';
  import { fade, fly, scale, blur } from 'svelte/transition';
  import { nanoid } from 'nanoid';
  import { 
    LAYER_DEFINITIONS, 
    shouldReduceMotion,
    getLayerDelay,
    type DafelBandaProps,
    type AnimationType,
    type AnimationConfig,
    type ThemeConfig,
    type AccessibilityConfig,
    type PerformanceConfig
  } from '../../shared/types';
  import SVGDefinitions from './components/SVGDefinitions.svelte';

  // Props
  export let animation: AnimationType = 'fadeIn';
  export let width: number = 1280;
  export let height: number = 720;
  export let interactive: boolean = false;
  export let className: string = '';
  export let ariaLabel: string = 'Dafel Banda animated decorative element';
  export let reducedMotion: boolean = false;
  export let lazy: boolean = true;
  export let performance: 'low' | 'medium' | 'high' = 'medium';
  export let animationConfig: AnimationConfig | undefined = undefined;
  export let accessibilityConfig: AccessibilityConfig | undefined = undefined;
  export let themeConfig: ThemeConfig | undefined = undefined;

  // Event dispatcher
  const dispatch = createEventDispatcher<{
    hover: Event;
    click: Event;
    focus: Event;
    load: void;
    error: Error;
    animationStart: void;
    animationEnd: void;
  }>();

  // Component state
  let svgElement: SVGSVGElement;
  let instanceId = nanoid();
  let isVisible = false;
  let isPlaying = false;
  let intersectionObserver: IntersectionObserver;

  // Animation stores
  const containerOpacity = tweened(0, { duration: 1200, easing: cubicOut });
  const containerScale = tweened(0.95, { duration: 1200, easing: cubicOut });
  const containerY = tweened(50, { duration: 1200, easing: cubicOut });

  // Layer animation stores
  const layerAnimations = LAYER_DEFINITIONS.map((layer, index) => ({
    opacity: tweened(0, { 
      duration: 1000, 
      delay: getLayerDelay(index),
      easing: cubicOut 
    }),
    x: tweened(0, { 
      duration: animationConfig?.duration || 4000,
      easing: sineInOut 
    }),
    y: tweened(0, { 
      duration: animationConfig?.duration || 4000,
      easing: sineInOut 
    }),
    scale: tweened(1, { 
      duration: 3000,
      easing: sineInOut 
    })
  }));

  // Reactive values
  $: motionReduced = shouldReduceMotion({ reducedMotion, accessibilityConfig });
  $: finalAnimation = motionReduced ? 'none' : animation;
  $: viewBox = `0 0 ${width} ${height}`;
  $: layerData = LAYER_DEFINITIONS;

  $: componentClasses = [
    'dafel-banda',
    'dafel-banda--animated',
    className,
    {
      'dafel-banda--interactive': interactive,
      'dafel-banda--reduced-motion': motionReduced,
      'dafel-banda--visible': isVisible,
      [`dafel-banda--${performance}`]: performance !== 'medium',
      [`dafel-banda--${finalAnimation}`]: finalAnimation !== 'none',
    }
  ].filter(Boolean).join(' ');

  $: componentStyles = {
    overflow: 'hidden',
    ...(performance === 'high' && {
      willChange: 'transform, opacity',
      transform: 'translateZ(0)',
    }),
  };

  // Watch for visibility changes
  $: if (isVisible && !motionReduced) {
    startAnimations();
  }

  // Methods
  function startAnimations() {
    if (isPlaying || finalAnimation === 'none') return;
    
    isPlaying = true;
    dispatch('animationStart');

    // Container animation
    containerOpacity.set(1);
    containerScale.set(1);
    containerY.set(0);

    // Layer animations based on type
    switch (finalAnimation) {
      case 'fadeIn':
        startFadeInAnimation();
        break;
      case 'wave':
        startWaveAnimation();
        break;
      case 'pulse':
        startPulseAnimation();
        break;
      case 'morphing':
        startMorphingAnimation();
        break;
    }
  }

  function startFadeInAnimation() {
    layerData.forEach((layer, index) => {
      setTimeout(() => {
        layerAnimations[index].opacity.set(layer.opacity);
      }, getLayerDelay(index));
    });

    // Animation complete after longest delay + duration
    const totalDuration = getLayerDelay(layerData.length - 1) + 1000;
    setTimeout(() => {
      dispatch('animationEnd');
    }, totalDuration);
  }

  function startWaveAnimation() {
    layerData.forEach((layer, index) => {
      layerAnimations[index].opacity.set(layer.opacity);
      
      // Create wave motion
      const waveAnimation = () => {
        const anim = layerAnimations[index];
        anim.x.set(-8).then(() => 
          anim.x.set(8).then(() => 
            anim.x.set(-8).then(() => {
              if (isPlaying && finalAnimation === 'wave') {
                waveAnimation();
              }
            })
          )
        );
        
        anim.y.set(-3).then(() => 
          anim.y.set(3).then(() => 
            anim.y.set(-3)
          )
        );
      };

      setTimeout(waveAnimation, getLayerDelay(index));
    });
  }

  function startPulseAnimation() {
    layerData.forEach((layer, index) => {
      layerAnimations[index].opacity.set(layer.opacity);
      
      // Create pulse motion
      const pulseAnimation = () => {
        const anim = layerAnimations[index];
        const baseOpacity = layer.opacity;
        const maxOpacity = Math.min(baseOpacity + 0.15, 1);
        
        anim.opacity.set(maxOpacity).then(() => 
          anim.opacity.set(baseOpacity).then(() => {
            if (isPlaying && finalAnimation === 'pulse') {
              setTimeout(pulseAnimation, 100);
            }
          })
        );
        
        anim.scale.set(1.02).then(() => 
          anim.scale.set(1)
        );
      };

      setTimeout(pulseAnimation, getLayerDelay(index));
    });
  }

  function startMorphingAnimation() {
    // Simplified morphing - in production, use proper SVG morphing
    layerData.forEach((layer, index) => {
      layerAnimations[index].opacity.set(layer.opacity);
      
      const morphAnimation = () => {
        const anim = layerAnimations[index];
        anim.scale.set(1.01).then(() => 
          anim.scale.set(0.99).then(() => 
            anim.scale.set(1).then(() => {
              if (isPlaying && finalAnimation === 'morphing') {
                setTimeout(morphAnimation, 200);
              }
            })
          )
        );
      };

      setTimeout(morphAnimation, getLayerDelay(index));
    });
  }

  function stopAnimations() {
    isPlaying = false;
    
    // Reset all animations
    containerOpacity.set(0);
    containerScale.set(0.95);
    containerY.set(50);
    
    layerAnimations.forEach(anim => {
      anim.opacity.set(0);
      anim.x.set(0);
      anim.y.set(0);
      anim.scale.set(1);
    });
  }

  function getTabIndex(): number | undefined {
    return interactive && accessibilityConfig?.focusable 
      ? accessibilityConfig.tabIndex || 0 
      : undefined;
  }

  function handleInteraction(event: Event) {
    if (!interactive) return;
    
    switch (event.type) {
      case 'mouseenter':
      case 'mouseover':
        dispatch('hover', event);
        break;
      case 'click':
        dispatch('click', event);
        break;
      case 'focus':
        dispatch('focus', event);
        break;
    }
  }

  function handleLayerInteraction(event: Event, layerId: number) {
    if (!interactive) return;
    handleInteraction(event);
  }

  function handleLoad() {
    dispatch('load');
  }

  function handleLayerError(error: Error) {
    console.error('Layer error:', error);
    dispatch('error', error);
  }

  // Lifecycle
  onMount(() => {
    if (!lazy) {
      isVisible = true;
      return;
    }

    intersectionObserver = new IntersectionObserver(
      ([entry]) => {
        isVisible = entry.isIntersecting;
      },
      { threshold: 0.3, rootMargin: '-100px' }
    );

    intersectionObserver.observe(svgElement);
  });

  onDestroy(() => {
    intersectionObserver?.disconnect();
    stopAnimations();
  });

  // Public API
  export function play() {
    isVisible = true;
    startAnimations();
  }

  export function pause() {
    isPlaying = false;
  }

  export function reset() {
    stopAnimations();
    isVisible = false;
  }

  export function getSvgElement(): SVGSVGElement {
    return svgElement;
  }
</script>

<svg
  bind:this={svgElement}
  {width}
  {height}
  viewBox={viewBox}
  xmlns="http://www.w3.org/2000/svg"
  class={componentClasses}
  style={Object.entries(componentStyles)
    .map(([key, value]) => `${key}: ${value}`)
    .join('; ')}
  aria-label={ariaLabel}
  role={accessibilityConfig?.role || 'img'}
  tabindex={getTabIndex()}
  on:mouseenter={handleInteraction}
  on:click={handleInteraction}
  on:focus={handleInteraction}
  on:load={handleLoad}
  opacity={$containerOpacity}
  transform="scale({$containerScale}) translateY({$containerY}px)"
>
  <!-- SVG Definitions -->
  <SVGDefinitions {instanceId} {themeConfig} />

  <!-- Background -->
  <rect 
    {width} 
    {height} 
    fill={themeConfig?.colors?.background || '#F8FBFD'} 
  />

  <!-- Animated Layers -->
  {#each layerData as layer, index (layer.id)}
    <g
      id="layer-{layer.id}-{layer.name}-{instanceId}"
      class="band-layer"
      class:band-layer--has-grid={layer.hasGrid}
      class:band-layer--interactive={interactive}
      opacity={$layerAnimations[index].opacity}
      transform="translate({$layerAnimations[index].x}, {$layerAnimations[index].y}) scale({$layerAnimations[index].scale})"
      style:cursor={interactive ? 'pointer' : 'default'}
      style:filter={layer.hasFilter && performance === 'high' ? `url(#${layer.filter}-${instanceId})` : undefined}
      on:mouseenter={(e) => interactive && handleLayerInteraction(e, layer.id)}
      on:click={(e) => interactive && handleLayerInteraction(e, layer.id)}
      on:focus={(e) => interactive && handleLayerInteraction(e, layer.id)}
    >
      <!-- Base path -->
      <path
        d={layer.path}
        fill="url(#{layer.gradient}-{instanceId})"
        class="band-path"
      />

      <!-- Grid overlay -->
      {#if layer.hasGrid}
        <path
          d={layer.path}
          fill="url(#{layer.gridPattern}-{instanceId})"
          class="band-grid-overlay"
        />
      {/if}
    </g>
  {/each}
</svg>

<style>
  :global(.dafel-banda) {
    display: block;
    max-width: 100%;
    height: auto;
  }

  :global(.dafel-banda--animated) {
    transition: all 0.3s ease;
  }

  :global(.dafel-banda--interactive) {
    cursor: pointer;
  }

  :global(.band-layer) {
    transition: all 0.3s ease;
  }

  :global(.band-layer--interactive:hover) {
    opacity: 1 !important;
  }

  :global(.band-path) {
    vector-effect: non-scaling-stroke;
  }

  :global(.band-grid-overlay) {
    pointer-events: none;
  }

  :global(.dafel-banda--reduced-motion),
  :global(.dafel-banda--reduced-motion *) {
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.01ms !important;
  }

  @media (prefers-reduced-motion: reduce) {
    :global(.dafel-banda),
    :global(.dafel-banda *) {
      animation-duration: 0.01ms !important;
      animation-iteration-count: 1 !important;
      transition-duration: 0.01ms !important;
    }
  }

  @media (max-width: 768px) {
    :global(.dafel-banda) {
      max-height: 300px;
    }
  }
</style>

// libs/dafel-banda-vectorization/components/vue/src/DafelBandaAnimated.vue
<!--
  Dafel Banda Animated Vue 3 Component
  Full-featured component with Vue Motion animations
-->

<template>
  <svg
    ref="svgRef"
    :width="width"
    :height="height"
    :viewBox="`0 0 ${width} ${height}`"
    xmlns="http://www.w3.org/2000/svg"
    :class="componentClasses"
    :style="componentStyles"
    :aria-label="ariaLabel"
    :role="accessibilityConfig?.role || 'img'"
    :tabindex="interactive && accessibilityConfig?.focusable ? accessibilityConfig.tabIndex || 0 : undefined"
    @mouseenter="handleInteraction"
    @click="handleInteraction"
    @focus="handleInteraction"
    @load="handleLoad"
    v-motion
    :initial="containerVariants.hidden"
    :enter="containerVariants.visible"
    :leave="containerVariants.hidden"
  >
    <!-- SVG Definitions -->
    <SVGDefinitions 
      :instance-id="instanceId"
      :theme-config="themeConfig"
    />

    <!-- Background -->
    <rect 
      :width="width" 
      :height="height" 
      :fill="themeConfig?.colors?.background || '#F8FBFD'" 
    />

    <!-- Animated Layers -->
    <g
      v-for="(layer, index) in layerData"
      :key="layer.id"
      :id="`layer-${layer.id}-${layer.name}-${instanceId}`"
      :class="getLayerClasses(layer)"
      :opacity="layer.opacity"
      :style="getLayerStyles(layer)"
      v-motion
      :initial="getLayerInitial(index)"
      :enter="getLayerEnter(layer, index)"
      :variants="layerVariants[finalAnimation]"
      :custom="getLayerCustomProps(layer, index)"
      @mouseenter="interactive ? (e: Event) => handleLayerInteraction(e, layer.id) : undefined"
      @click="interactive ? (e: Event) => handleLayerInteraction(e, layer.id) : undefined"
      @focus="interactive ? (e: Event) => handleLayerInteraction(e, layer.id) : undefined"
    >
      <!-- Base path -->
      <path
        :d="layer.path"
        :fill="`url(#${layer.gradient}-${instanceId})`"
        class="band-path"
      />

      <!-- Grid overlay -->
      <path
        v-if="layer.hasGrid"
        :d="layer.path"
        :fill="`url(#${layer.gridPattern}-${instanceId})`"
        class="band-grid-overlay"
      />
    </g>
  </svg>
</template>

<script setup lang="ts">
import { computed, ref, reactive, onMounted, watch } from 'vue'
import { useMotion } from '@vueuse/motion'
import { useIntersectionObserver } from '@vueuse/core'
import { nanoid } from 'nanoid'
import { 
  DafelBandaProps, 
  LAYER_DEFINITIONS, 
  shouldReduceMotion,
  getLayerDelay
} from '../../shared/types'
import SVGDefinitions from './components/SVGDefinitions.vue'

// Props
const props = withDefaults(defineProps<DafelBandaProps>(), {
  animation: 'fadeIn',
  width: 1280,
  height: 720,
  interactive: false,
  className: '',
  ariaLabel: 'Dafel Banda animated decorative element',
  reducedMotion: false,
  lazy: true,
  performance: 'medium'
})

// Emits
const emit = defineEmits<{
  hover: [event: Event]
  click: [event: Event]
  focus: [event: Event]
  load: []
  error: [error: Error]
}>()

// Template refs
const svgRef = ref<SVGSVGElement>()

// Reactive state
const state = reactive({
  instanceId: nanoid(),
  isVisible: false,
  isPlaying: false
})

// Intersection observer for visibility
const { stop } = useIntersectionObserver(
  svgRef,
  ([{ isIntersecting }]) => {
    state.isVisible = isIntersecting
  },
  { threshold: 0.3, rootMargin: '-100px' }
)

// Computed properties
const motionReduced = computed(() => 
  shouldReduceMotion({ 
    reducedMotion: props.reducedMotion, 
    accessibilityConfig: props.accessibilityConfig 
  })
)

const finalAnimation = computed(() => 
  motionReduced.value ? 'none' : props.animation
)

const layerData = computed(() => LAYER_DEFINITIONS)

const instanceId = computed(() => state.instanceId)

const componentClasses = computed(() => [
  'dafel-banda',
  'dafel-banda--animated',
  {
    'dafel-banda--interactive': props.interactive,
    'dafel-banda--reduced-motion': motionReduced.value,
    'dafel-banda--visible': state.isVisible,
    [`dafel-banda--${props.performance}`]: props.performance !== 'medium',
    [`dafel-banda--${finalAnimation.value}`]: finalAnimation.value !== 'none',
  },
  props.className
])

const componentStyles = computed(() => ({
  overflow: 'hidden',
  ...(props.performance === 'high' && {
    willChange: 'transform, opacity',
    transform: 'translateZ(0)'
  })
}))

// Animation variants
const containerVariants = computed(() => ({
  hidden: {
    opacity: 0,
    scale: 0.95,
    y: 50
  },
  visible: {
    opacity: 1,
    scale: 1,
    y: 0,
    transition: {
      duration: props.animationConfig?.duration || 1200,
      ease: props.animationConfig?.easing || 'ease-out',
      staggerChildren: 100
    }
  }
}))

const layerVariants = computed(() => ({
  fadeIn: {
    hidden: { opacity: 0, y: 30, scale: 0.95 },
    visible: (custom: any) => ({
      opacity: custom.baseOpacity,
      y: 0,
      scale: 1,
      transition: {
        duration: 1000,
        delay: custom.delay,
        ease: 'ease-out'
      }
    })
  },
  wave: {
    animate: (custom: any) => ({
      x: [-8, 8, -8],
      y: [-3, 3, -3],
      transition: {
        duration: props.animationConfig?.duration || 4000,
        delay: custom.delay,
        repeat: props.animationConfig?.repeat === false ? 0 : Infinity,
        ease: 'ease-in-out',
        repeatType: 'reverse'
      }
    })
  },
  pulse: {
    animate: (custom: any) => ({
      scale: [1, 1.02, 1],
      opacity: [
        custom.baseOpacity,
        Math.min(custom.baseOpacity + 0.15, 1),
        custom.baseOpacity
      ],
      transition: {
        duration: 3000,
        delay: custom.delay,
        repeat: props.animationConfig?.repeat === false ? 0 : Infinity,
        ease: 'ease-in-out'
      }
    })
  },
  interactive: {
    rest: { scale: 1, y: 0 },
    hover: (custom: any) => ({
      scale: 1.02,
      y: -2,
      opacity: Math.min(custom.baseOpacity + 0.1, 1),
      transition: {
        duration: 300,
        ease: 'ease-out'
      }
    }),
    tap: { scale: 0.98 }
  }
}))

// Methods
const getLayerClasses = (layer: any) => [
  'band-layer',
  {
    'band-layer--has-grid': layer.hasGrid,
    'band-layer--interactive': props.interactive
  }
]

const getLayerStyles = (layer: any) => ({
  cursor: props.interactive ? 'pointer' : 'default',
  ...(layer.hasFilter && props.performance === 'high' && {
    filter: `url(#${layer.filter}-${instanceId.value})`
  })
})

const getLayerInitial = (index: number) => {
  switch (finalAnimation.value) {
    case 'fadeIn':
      return 'hidden'
    default:
      return {}
  }
}

const getLayerEnter = (layer: any, index: number) => {
  switch (finalAnimation.value) {
    case 'fadeIn':
      return state.isVisible ? 'visible' : 'hidden'
    case 'wave':
    case 'pulse':
      return 'animate'
    case 'interactive':
      return props.interactive ? 'rest' : {}
    default:
      return {}
  }
}

const getLayerCustomProps = (layer: any, index: number) => ({
  baseOpacity: layer.opacity,
  delay: getLayerDelay(index),
  duration: 4000 - getLayerDelay(index),
  originalPath: layer.path
})

const handleInteraction = (event: Event) => {
  if (!props.interactive) return
  
  switch (event.type) {
    case 'mouseenter':
    case 'mouseover':
      emit('hover', event)
      break
    case 'click':
      emit('click', event)
      break
    case 'focus':
      emit('focus', event)
      break
  }
}

const handleLayerInteraction = (event: Event, layerId: number) => {
  if (!props.interactive) return
  
  switch (event.type) {
    case 'mouseenter':
      emit('hover', event)
      break
    case 'click':
      emit('click', event)
      break
    case 'focus':
      emit('focus', event)
      break
  }
}

const handleLoad = () => {
  emit('load')
}

// Watch for visibility changes to control animations
watch(() => state.isVisible, (isVisible) => {
  if (isVisible) {
    state.isPlaying = true
  }
})

// Cleanup
onMounted(() => {
  return () => {
    stop()
  }
})

// Expose public API
defineExpose({
  svgElement: svgRef,
  isVisible: computed(() => state.isVisible),
  isPlaying: computed(() => state.isPlaying),
  instanceId,
  play: () => { state.isPlaying = true },
  pause: () => { state.isPlaying = false },
  reset: () => { 
    state.isPlaying = false
    // Reset to initial state
  }
})
</script>

<style scoped>
.dafel-banda {
  display: block;
  max-width: 100%;
  height: auto;
}

.dafel-banda--animated {
  transition: all 0.3s ease;
}

.dafel-banda--interactive {
  cursor: pointer;
}

.band-layer {
  transition: all 0.3s ease;
}

.band-layer--interactive:hover {
  opacity: 1 !important;
}

.band-path {
  vector-effect: non-scaling-stroke;
}

.band-grid-overlay {
  pointer-events: none;
}

.dafel-banda--reduced-motion,
.dafel-banda--reduced-motion * {
  animation-duration: 0.01ms !important;
  animation-iteration-count: 1 !important;
  transition-duration: 0.01ms !important;
}

@media (prefers-reduced-motion: reduce) {
  .dafel-banda,
  .dafel-banda * {
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.01ms !important;
  }
}

@media (max-width: 768px) {
  .dafel-banda {
    max-height: 300px;
  }
}
</style>
